<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Name' => 'Название',
    'Add product' => 'Добавить товар',
    'Category' => 'Категория',
    'Update' => 'Обновить',
    'Save' => 'Сохранить',
    'Status' => 'Статус',
    'Links to pictures' => 'Ссылки на картинки',
    'Product link' => 'Ссылка на товар',
    'Products' => 'Продукты',
    'Product Categories' => 'Категории товаров',
    'Create Product Category' => 'Добавить категорию товаров',
    'Update Product Category' => 'Изменить категорию товаров',
    'Product Count' => 'Количество',
    'Images' => 'Картинки',
    'Add products' => 'Добавить товары',
    'Product Lists' => 'Склад',
    'Cost' => 'Цена',
    'Link' => 'Ссылка',
    'Delete' => 'Удалить',
    'Good products' => 'Хорошие товары',
    'Bad products' => 'Плохие товары',
    'Need products' => 'Нужно товары',
    'Comments' => 'Комментарий',
    'Date of purchase' => 'Дата покупки',
    //materials
    'Materials' => 'Материалы',
    'Create Material' => 'Добавить материал',
    'Update Material' => 'Изменить материал',
    'Material Categories' => 'Категории материалов',
    'Create Material Category' => 'Создать категорию материалов',
    'Update Material Category' => 'Изменить категорию материалов',
];
